version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fabian
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: portafolio
